apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-api-server
  template:
    metadata:
      labels:
        app: chat-api-server
    spec:
      containers:
        - name: openim-chat-api-container
          image: openim-chat-api:test
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: CHATENV_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-redis-secret
                  key: redis-password
            - name: IMENV_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_username
            - name: CHATENV_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_password

          volumeMounts:
            - name: openim-chat-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10008
      volumes:
        - name: openim-chat-config
          configMap:
            name: openim-chat-config
