apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-rpc-server
  template:
    metadata:
      labels:
        app: admin-rpc-server
    spec:
      containers:
        - name: openim-admin-rpc-container
          image: openim/openim-admin-rpc:v3.8.3
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: CHATENV_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: CHATENV_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_openim_password

          volumeMounts:
            - name: openim-chat-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 30200
      volumes:
        - name: openim-chat-config
          configMap:
            name: openim-chat-config
