zookeeper:
  schema: openim
  zkAddr:
    - 127.0.0.1:2181
  userName: ""
  password: ""
chatapi:
  openImChatApiPort: [ 10008 ]
  listenIP: 0.0.0.0
adminapi:
  openImAdminApiPort: [ 10009 ]
  listenIP: 0.0.0.0
rpcport:
  openImAdminPort: [ 30200 ]
  openImChatPort: [ 30300 ]
rpcregistername:
  openImAdminName: admin
  openImChatName: chat
mysql:
  dbMysqlDatabaseName: openim_enterprise

tokenPolicy:
  accessSecret: "openIM123"
  accessExpire: 86400

verifycode:
  validTime: 300 # 验证码有效时间
  validCount: 5 # 验证码有效次数
  uintTime: 86400 # 单位时间间隔
  maxCount: 10 # 单位时间内最大获取次数
  superCode: "666666" # 超级验证码(只有use为空时使用)
  len: 6 # 验证码长度
  use: "" # 使用的验证码服务(use: "Ali")
  Ali:
    endpoint: "dysmsapi.aliyuncs.com"
    accessKeyId: ""
    accessKeySecret: ""
    signName: ""
    verificationCodeTemplateCode: ""

proxyheader: "" # 获取ip的header 空字符串没有代理
#proxyheader: "X-Forwarded-For"